### ISSUE TITLE
Support Nullability

### ISSUE THREAD

**Issue by ultraon** [wrike/memoize_dart#11]
Is it supposed to support Nullability?

**Comment by missvalentinep** [comment]
Closing this issue as null-safety support has been added in version 3.0.0

**Comment by missvalentinep** [comment]
Reopening the issue as we're currently unable to publish the new version of the package due to the problems with our pub account. Planning to fix this in the beginning of the next week. I do apologize for the inconvenience.

**Comment by kostaa** [comment]
Have you been able to resolve your pub account issue?

**Comment by sinegovsky-ivan** [comment]
@kostaa I hope today we will resolve the issue.

**Comment by missvalentinep** [comment]
@kostaa the package has been published, thank you for your patience! https://pub.dev/packages/memoize/versions/3.0.0
