### ISSUE TITLE
Support Dart 2.1

### ISSUE THREAD

**Issue by sir-boformer** [wrike/memoize_dart#8]
the version constraints in the pubspec.yaml make it impossible to use memoize with the latest flutter version.

**Comment by Aetet** [comment]
Thanks for issue! We publish new version in this week.

**Comment by 24601** [comment]
Until the official 2/2.1 support is out, I have a total hack job fork that (so far) works. 

Yes, it's a workaround. Yes, it's hack-ish. Yes, so many better ways of going about it. But, it got me working until the officially supported 2.1 build is out, so if it can help you, just override your memoize dep using:

```
dependency_overrides:
  memoize:
    git: git://github.com/VoltaireApp/memoize_dart.git
```

**Comment by Aetet** [comment]
Merged at https://github.com/wrike/memoize_dart/pull/9
